apiVersion: github.jet.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: default
spec:
  credentials:
    source: Secret
    secretRef:
      name: github-creds
      namespace: crossplane-system
      key: credentials
